# Generated by Django 4.1.3 on 2022-11-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_photo_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
